// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FilmWebProject.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeReleaseDateType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeReleaseDateType));
        
        string IMigrationMetadata.Id
        {
            get { return "201902041230159_changeReleaseDateType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
